// INCLUDE FILE generated by "Pelles C for Windows, version 9.00".

#define IDD_MAINDIALOG                1001
#define MAIN_DIALOGCAPTION            "ChargeOn - The Laptop Battery Conditioner"

#define IDM_MENU                      1111
#define IDM_FILE_EXIT                 1121
#define IDM_TOOLS_SETTINGS            1131
#define IDM_TOOLS_UPDATE              1132
#define IDM_TOOLS_DRIVER              1133
#define IDM_HELP_ABOUT                1141

#define IDC_PERCENTCHARGED            1201
#define IDC_PROGRESS                  1202
#define IDC_CHARGING                  1203
#define IDC_MIN_LABEL                 1204
#define IDC_MIN_EDIT                  1205
#define IDC_MIN_UPDOWN                1206
#define IDC_MAX_LABEL                 1207
#define IDC_MAX_EDIT                  1208
#define IDC_MAX_UPDOWN                1209
#define IDC_STATUS                    1210
#define IDC_STATUS2                   1211
#define IDC_SWITCH_OUTLET             1212

#define IDD_SETTINGS_DIALOG           2001

#define IDD_BATTERY_PROPS_DIALOG      2101
#define  IDC_CHECK_INTERVAL_LBL       2102
#define  IDC_CHECK_INTERVAL           2103
#define  IDC_UPDATE_DISPLAY_LOG_LBL   2104
#define   IDC_UPDATE_EVERYCHECK       2105
#define   IDC_UPDATE_ONCHANGE         2106

#define IDD_OUTLET_PROPS_DIALOG       2201
#define  IDG_GROUP_OUTLET_HARDWARE    2210
#define   IDC_OUTLET_ON_CODE_LBL      2211
#define   IDC_OUTLET_ON_CODE          2212
#define   IDC_OUTLET_OFF_CODE_LBL     2213
#define   IDC_OUTLET_OFF_CODE         2214
#define   IDC_OUTLET_CODELENGTH_LBL   2215
#define   IDC_OUTLET_CODELENGTH       2216
#define   IDC_OUTLET_PROTOCOL_LBL     2217
#define   IDC_OUTLET_PROTOCOL         2218
#define   IDC_OUTLET_PULSELENGTH_LBL  2219
#define   IDC_OUTLET_PULSELENGTH      2220
#define   IDC_OUTLET_LEARN            2221
#define  IDG_GROUP_OUTLET_USER        2250
#define   IDC_OUTLET_PULSEREPEATS_LBL 2251
#define   IDC_OUTLET_PULSEREPEATS     2252
#define   IDC_TURNON_BEFOREQUIT_LBL   2253
#define   IDC_TURNON_BEFOREQUIT       2254


// KJB: Placeholder for logging option controls

//#define IDD_HELPABOUTDIALOG           2301

#define IDT_TIMER1                    9001

#define ICON_256                      9101
#define ICON_48                       9102
#define ICON_32                       9103
#define ICON_16                       9104
